routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Home Route - default home page
Route::get('/', 'PageController@home');

Route::get('/events', 'EventController@events');

Route::get('/past-events', 'EventController@pastEvents');

Route::get('/events/{event}', [
	  'uses' => 'EventController@eventDetails',
	  'as' => 'event.index'
]);

Route::post('search', ['as' => 'search', 'uses' => 'SearchController@search']);
//Route::get('search', ['as' => 'search', 'uses' => 'SearchController@show']);

//refactor and use Ajax
Route::post('/', [
	  'uses' => 'SubscribeController@store',
	  'as' => 'subscriber.store'
]);

//BLOG ROUTES
Route::get('/blog', [
  'uses' => 'BlogController@index',
  'as' => 'blog.index'
]);

Route::get('/blog/{post}', [
  'uses' => 'BlogController@single',
  'as' => 'blog.single'
]);

Route::get('/blog/category/{category}', [
  'uses' => 'BlogController@category',
  'as' => 'blog.category'
]);

Route::get('/blog/author/{author}', [
  'uses' => 'BlogController@author',
  'as' => 'blog.author'
]);

Auth::routes();

// Dashboard Routes
Route::get('/admin', [
	  'uses' => 'Backend\DashboardController@index',
	  'as' => 'admin.dashboard'
]);

Route::group(['middleware' => 'App\Http\Middleware\PasswordMiddleware'], function()
{
// Route::group(['middleware' => 'App\Http\Middleware\PasswordMiddleware'], function()
// {
	Route::patch('/admin/users/{user}/change-password', [
		'uses' => 'Backend\AdminUserController@updatePassword',
		'as' => 'admin.users.updatePassword'
	]);
//Lists
Route::resource('/admin/lists', 'Backend\ListController', [
	  'names' => [
			'store' => 'admin.lists.store',
			'index' => 'admin.lists.index',
			'create' => 'admin.lists.create',
			'update' => 'admin.lists.update',
			'destroy' => 'admin.lists.destroy',
			'edit' => 'admin.lists.edit',
	  ]
]);

//Users
Route::resource('/admin/users', 'Backend\AdminUserController', [
	  'names' => [
			'store' => 'admin.users.store',
			'index' => 'admin.users.index',
			'create' => 'admin.users.create',
			'update' => 'admin.users.update',
			'destroy' => 'admin.users.destroy',
			'edit' => 'admin.users.edit',
	  ]
]);

	Route::get('/admin/users/{user}/change-password', 'Backend\AdminUserController@changePassword');
}); //END PASSWORD MIDDLEWARE

Route::patch('/admin/users/{user}/change-password', [
	  'uses' => 'Backend\AdminUserController@updatePassword',
	  'as' => 'admin.users.updatePassword'
]);

Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function()
{
	//Can only access these routes if the logged in user as an Admin or Super Admin

	//Users
	Route::resource('/admin/users', 'Backend\AdminUserController', [
		  'names' => [
				'store' => 'admin.users.store',
				'index' => 'admin.users.index',
				'create' => 'admin.users.create',
				'show' => 'admin.users.show',
				'update' => 'admin.users.update',
				'destroy' => 'admin.users.destroy',
				'edit' => 'admin.users.edit',
		  ]
	]);

	// Blog
	Route::resource('/admin/posts', 'Backend\AdminBlogController', [
		  'names' => [
				'store' => 'admin.blog.store',
				'index' => 'admin.blog.index',
				'create' => 'admin.blog.create',
				'show' => 'admin.blog.show',
				'update' => 'admin.blog.update',
				'destroy' => 'admin.blog.destroy',
				'edit' => 'admin.blog.edit',
		  ]
	]);
	Route::put('admin/posts/{post}/restore', [
		  'uses' => 'Backend\AdminBlogController@restore',
		  'as' => 'admin.blog.restore'
	]);
	Route::delete('admin/posts/{post}/force', [
		  'uses' => 'Backend\AdminBlogController@forceDestroy',
		  'as' => 'admin.blog.force-destroy'
	]);

	//categories
	Route::resource('/admin/categories', 'Backend\AdminCategoryController', [
		  'names' => [
				'store' => 'admin.categories.store',
				'index' => 'admin.categories.index',
				'create' => 'admin.categories.create',
				'show' => 'admin.categories.show',
				'update' => 'admin.categories.update',
				'destroy' => 'admin.categories.destroy',
				'edit' => 'admin.categories.edit',
		  ]
	]);

	// Pages
	Route::resource('/admin/pages', 'Backend\AdminPageController', [
		  'names' => [
				'store' => 'admin.pages.store',
				'index' => 'admin.pages.index',
				'create' => 'admin.pages.create',
				'show' => 'admin.pages.show',
				'update' => 'admin.pages.update',
				'destroy' => 'admin.pages.destroy',
				'edit' => 'admin.pages.edit',
		  ]
	]);
	Route::put('admin/pages/{page}/restore', [
		  'uses' => 'Backend\AdminPageController@restore',
		  'as' => 'admin.pages.restore'
	]);
	Route::delete('admin/pages/{page}/force', [
		  'uses' => 'Backend\AdminPageController@forceDestroy',
		  'as' => 'admin.pages.force-destroy'
	]);

	// Events
	Route::resource('/admin/events', 'Backend\AdminEventController', [
		  'names' => [
				'store' => 'admin.events.store',
				'index' => 'admin.events.index',
				'create' => 'admin.events.create',
				'show' => 'admin.events.show',
				'update' => 'admin.events.update',
				'destroy' => 'admin.events.destroy',
				'edit' => 'admin.events.edit',
		  ]]);


	// Uploads
	Route::resource('/admin/uploads', 'UploadController', [
			'names' => [
				'store' => 'admin.uploads.store',
				'index' => 'admin.uploads.index',
				'create' => 'admin.uploads.create',
				'update' => 'admin.uploads.update',
				'destroy' => 'admin.uploads.destroy',
				'edit' => 'admin.uploads.edit',
			]]);
	Route::get('/admin/uploads/ajax/pages/{id}', [
		'as' => 'admin.uploads.ajax.attachments',
		'uses' => 'UploadController@ajaxPages'
	]);
	Route::get('/admin/uploads/ajax/posts/{id}', [
		'as' => 'admin.uploads.ajax.attachments2',
		'uses' => 'UploadController@ajaxPosts'
	]);
	Route::put('/admin/uploads/hide/{id}', [
		'as' => 'admin.uploads.hideToggle',
		'uses' => 'UploadController@hideToggle'
	]);


	// Mailing Lists
	Route::resource('/admin/lists', 'Backend\ListController', [
		  'names' => [
				'store' => 'admin.lists.store',
				'index' => 'admin.lists.index',
				'create' => 'admin.lists.create',
				'show' => 'admin.lists.show',
				'update' => 'admin.lists.update',
				'destroy' => 'admin.lists.destroy',
				'edit' => 'admin.lists.edit',
		  ]
	]);
	Route::put('admin/lists/{list}/restore', [
		  'uses' => 'Backend\ListController@restore',
		  'as' => 'admin.lists.restore'
	]);
	Route::delete('admin/lists/{list}/force', [
		  'uses' => 'Backend\ListController@forceDestroy',
		  'as' => 'admin.lists.force-destroy'
	]);

	// Mailing Lists
	Route::resource('/admin/mail', 'Backend\MailController', [
		  'names' => [
				'store' => 'admin.mail.store',
				'index' => 'admin.mail.index',
				'create' => 'admin.mail.create',
				'show' => 'admin.mail.show',
				'update' => 'admin.mail.update',
				'destroy' => 'admin.mail.destroy',
				'edit' => 'admin.mail.edit',
		  ]
	]);
	Route::post('admin/mail/send/{id}', [
		'uses' => 'Backend\MailController@send',
		'as' => 'admin.mail.send'
		]);
	Route::post('/admin/menus/data', [
		'uses' => 'Backend\MenuController@data',
		'as' => 'admin.menus.data'
		]);
	Route::resource('/admin/menus', 'Backend\MenuController', [
	  'names' => [
			'store' => 'admin.menus.store',
			'index' => 'admin.menus.index',
			'create' => 'admin.menus.create',
			'update' => 'admin.menus.update',
			'destroy' => 'admin.menus.destroy',
			'edit' => 'admin.menus.edit',
	  ]
	]);
	Route::get('/admin/home/edit', [
		'uses' => 'Backend\HomeController@edit',
		'as' => 'admin.home.edit'
		]);
	Route::put('/admin/home/store/{id}', [
		'uses' => 'Backend\HomeController@update',
		'as' => 'admin.home.update'
		]);

}); //END ADMIN MIDDLEWARE

//Route::delete('/admin/users/{user}', 'Backend\AdminUserController@destroy');




// Default Catch-all for pages
Route::get('/{path}', 'PageController@show')->where('path', '(.*)')->name("pages.show");

app/Page.php
<?php
namespace App;
use Baum\Node;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;
use GrahamCampbell\Markdown\Facades\Markdown;
/**
* Page
*/
class Page extends Node {
  use SoftDeletes;
  protected $dates = ['published_at'];

  /**
   * Table name.
   *
   * @var string
   */
  protected $table = 'pages';

  protected $fillable = [
    'title',
    'excerpt',
    'body',
    'slug',
    'published_at',
    'menu_id'
  ];


  protected $parentColumn = 'parent_id';

  // /**
  //  * Column name for the left index.
  //  *
  //  * @var string
  //  */
  protected $leftColumn = 'lft';

  // /**
  //  * Column name for the right index.
  //  *
  //  * @var string
  //  */
  protected $rightColumn = 'rgt';

  // /**
  //  * Column name for the depth field.
  //  *
  //  * @var string
  //  */
  protected $depthColumn = 'depth';

  // /**
  //  * Column to perform the default sorting
  //  *
  //  * @var string
  //  */
  protected $orderColumn = null;

  // /**
  // * With Baum, all NestedSet-related fields are guarded from mass-assignment
  // * by default.
  // *
  // * @var array
  // */
  protected $guarded = array('id', 'parent_id', 'lft', 'rgt', 'depth');

  public function getIndentedAttribute() {
    // return str_repeat(html_entity_decode('&emsp;', 1), $this->depth) . $this->title;
    return $this->title;
  }

  public function attachments() {
    return $this->belongsToMany('App\Upload', 'page_upload');
  }

  public function menu() {
    return $this->belongsTo('App\Menu');
  }


  public function getPathAttribute()  {

    if ($this->isRoot()) {
      return $this->slug;
    } else {

    $ancestors = [];
    foreach ($this->getAncestorsAndSelf() as $node) {
      $ancestors[] = $node->slug;
    }
    if (!empty($ancestors)) {
      return implode('/', $ancestors);
    } else {
      return die('Something went wrong');
    }
  }
}

public function setPublishedAtAttribute($value) {
  $this->attributes['published_at'] = $value ?: NULL;
}

public function getDateAttribute($value) {
  return is_null($this->published_at) ? '' : $this->published_at->diffForHumans();
}

public function getBodyHtmlAttribute ($value) {
  return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
}

public function getExcerptHtmlAttribute ($value) {
  return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : NULL;
}

public function dateFormatted($showTimes = false) {
  $format = 'd/m/Y';
  if ($showTimes) {$format = $format . " H:i:s";}
  return $this->created_at->format($format);
}

public function getPublicationLabelAttribute() {
  if ($this->deleted_at) {
      return "<span class='label label-danger'>Trashed</span>";
  } elseif (!$this->published_at) {
      return "<span class='label label-warning'>Draft</span>";
  } elseif ($this->published_at && $this->published_at->isFuture() ) {
      return "<span class='label label-info'>Scheduled</span>";
  } else {
      return "<span class='label label-success'>Published</span>";
  }
}

//SCOPES
public function scopeLatestFirst($query) {
  return $query->orderBy('created_at', 'desc');
}

public function scopePublished($query) {
  return $query->where('published_at', '<=', Carbon::now());
}

public function scopeDraft($query) {
  return $query->where('published_at', '=', null);
}


}

resources/views/snippets/sidebar-blog-right.blade.php
<div class="col-md-4">
    <aside class="right-sidebar">

        {{-- <div class="search-widget">
            <div class="input-group">
              <input type="text" class="form-control input-lg" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-lg btn-default" type="button">
                    <i class="fa fa-search"></i>
                </button>
              </span>
            </div><!-- /input-group -->
        </div> --}}
        <div class="widget">
            <div class="widget-heading">
                <h4>Categories</h4>
            </div>
            <div class="widget-body">
                <ul class="categories">
                  @foreach($categories as $cat)
                    @if ($cat->count != 0)
                      <li>
                        <a href="{{route('blog.category', $cat->slug)}}"><i class="fa fa-angle-right"></i> {{$cat->title}}</a>
                        <span class="badge pull-right">{{$cat->count}}</span>
                      </li>
                    @endif
                  @endforeach

                </ul>
            </div>
        </div>

        <div class="widget">
            <div class="widget-heading">
                <h4>Popular Posts</h4>
            </div>
            <div class="widget-body">
                <ul class="popular-posts">

                    @foreach ($popularPosts as $post)
                      <li>
                          {{-- @if ($post->image)
                            <div class="post-image">
                                <a href="{{route('blog.single', $post->slug)}}">
                                    <img src="{{$post->image_url}}" />
                                </a>
                            </div>
                          @endif --}}
                          <div class="post-body">
                              <h6><a href="{{route('blog.single', $post->slug)}}">{{$post->title}}</a></h6>
                              <div class="post-meta">
                                  <span>{{$post->date}}</span>
                              </div>
                          </div>
                      </li>
                    @endforeach

                </ul>
            </div>
        </div>

        {{-- <div class="widget">
            <div class="widget-heading">
                <h4>Tags</h4>
            </div>
            <div class="widget-body">
                <ul class="tags">
                    <li><a href="#">PHP</a></li>
                    <li><a href="#">Codeigniter</a></li>
                    <li><a href="#">Yii</a></li>
                    <li><a href="#">Laravel</a></li>
                    <li><a href="#">Ruby on Rails</a></li>
                    <li><a href="#">jQuery</a></li>
                    <li><a href="#">Vue Js</a></li>
                    <li><a href="#">React Js</a></li>
                </ul>
            </div>
        </div> --}}
    </aside>
</div>